// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Base descartable que Prisma usa para validar migraciones en desarrollo.
    // Sólo hace falta localmente; en producción no se define.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
